import { Template, ObjectDefinition } from 'Features/NOTIFICATION/Template';

export const initTemplates: Template[] = [
    {
        id: 231,
        name: '[ENG] Thông báo kỳ đối soát được xác nhận thành công (gửi cho cả AWING và Partner)',
        objectType: 'RECONCILIATION_PERIOD',
        channelType: 'EMAIL',
        contentType: 'HTML',
        title: '[AWING – {n.Supplier.Name}] {n.Supplier.Name} - {o.Name} has been sucessfully confirmed ',
        content:
            '<p>Dear Sir/Madam,</p>\r\n<p id="first-content"></p>\r\n<p>Thank you.</p>\r\n<p style="color:red;font-size:12px; font-style: italic">This is an automated email from AWING Ad Point. For furter assistance related to the booking, please contact us at <a href=\'mailto:ads.booking@awing.vn\'>ads.booking@awing.vn</a> (do not reply to this email).</p>\r\n<script>\r\n(function () {\r\n\tvar firstContent = document.querySelector(\'#first-content\');\r\n\tfunction formatYearMonth(input) {\r\n\t\t// Chuyển đổi chuỗi đầu vào thành số\r\n\t\tvar year = Math.floor(input / 100); // Lấy 4 chữ số đầu cho năm\r\n\t\tvar month = input % 100; // Lấy 2 chữ số cuối cho tháng\r\n\t\t\r\n\t\t// Tạo đối tượng Date và định dạng tháng, năm\r\n\t\tvar date = new Date(year, month - 1); // Trừ 1 vì tháng trong Date bắt đầu từ 0\r\n\t\t\r\n\t\t// Lấy tháng và năm, xử lý để đảm bảo tháng có 2 chữ số\r\n\t\tvar formattedMonth = (date.getMonth() + 1).toString();\r\n\t\tif (formattedMonth.length < 2) {\r\n\t\t\tformattedMonth = \'0\' + formattedMonth; // Thêm số 0 vào trước nếu cần\r\n\t\t}\r\n\t\t\r\n\t\t// Kết quả là \'MM/YYYY\'\r\n\t\tvar formattedDate = formattedMonth + \'/\' + date.getFullYear();\r\n\t\t\r\n\t\treturn formattedDate;\r\n\t}\r\n\tvar period = "{o.Period}";\r\n\tvar supplierName = "{n.Supplier.Name}";\r\n\tvar reconPeriodName = supplierName + " - " + "Reconciliation Period " + formatYearMonth(period);\r\n\tfirstContent.innerHTML = "Your " + reconPeriodName + " has been successfully confirmed. Kindly prepare & send the reconciliation documents to AWING Accounting Team for payment processing.";\r\n})();\r\n</script>',
        configType: 'OBJECT_AND_CHANGED',
        outputFieldPermission: {
            objectDefinitionWithPermissions: [
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'id',
                        fieldPath: '.id.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'name',
                        fieldPath: '.name.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'objectType',
                        fieldPath: '.objectType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schemaId',
                        fieldPath: '.schemaId.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'channelType',
                        fieldPath: '.channelType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'contentType',
                        fieldPath: '.contentType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'title',
                        fieldPath: '.title.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'content',
                        fieldPath: '.content.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'configType',
                        fieldPath: '.configType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schema',
                        fieldPath: '.schema.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
            ],
        },
    },
    {
        id: 260,
        name: 'Biên bản nghiệm thu thực tế đợt v1.2 (VIE)',
        objectType: 'MEDIA_PLAN',
        contentType: 'HTML',
        channelType: 'FILE',
        configType: 'OBJECT_AND_CHANGED',
        outputFieldPermission: {
            objectDefinitionWithPermissions: [
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'id',
                        fieldPath: '.id.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'name',
                        fieldPath: '.name.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'objectType',
                        fieldPath: '.objectType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schemaId',
                        fieldPath: '.schemaId.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'channelType',
                        fieldPath: '.channelType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'contentType',
                        fieldPath: '.contentType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'title',
                        fieldPath: '.title.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'content',
                        fieldPath: '.content.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'configType',
                        fieldPath: '.configType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schema',
                        fieldPath: '.schema.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
            ],
        },
    },
    {
        id: 259,
        name: 'Biên bản nghiệm thu đợt v1.2 (VIE)',
        objectType: 'MEDIA_PLAN',
        contentType: 'HTML',
        channelType: 'FILE',
        configType: 'OBJECT_AND_CHANGED',

        outputFieldPermission: {
            objectDefinitionWithPermissions: [
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'id',
                        fieldPath: '.id.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'name',
                        fieldPath: '.name.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'objectType',
                        fieldPath: '.objectType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schemaId',
                        fieldPath: '.schemaId.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'channelType',
                        fieldPath: '.channelType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'contentType',
                        fieldPath: '.contentType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'title',
                        fieldPath: '.title.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'content',
                        fieldPath: '.content.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'configType',
                        fieldPath: '.configType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schema',
                        fieldPath: '.schema.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
            ],
        },
    },
    {
        id: 258,
        name: 'Biên bản nghiệm thu (ENG)',
        objectType: 'MEDIA_PLAN',
        contentType: 'HTML',
        channelType: 'FILE',
        configType: 'OBJECT_AND_CHANGED',

        outputFieldPermission: {
            objectDefinitionWithPermissions: [
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'id',
                        fieldPath: '.id.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'name',
                        fieldPath: '.name.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'objectType',
                        fieldPath: '.objectType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schemaId',
                        fieldPath: '.schemaId.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'channelType',
                        fieldPath: '.channelType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'contentType',
                        fieldPath: '.contentType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'title',
                        fieldPath: '.title.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'content',
                        fieldPath: '.content.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'configType',
                        fieldPath: '.configType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schema',
                        fieldPath: '.schema.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
            ],
        },
    },
    {
        id: 257,
        name: 'Biên bản nghiệm thu đợt cuối v1.1 (VIE)',
        objectType: 'MEDIA_PLAN',
        contentType: 'HTML',
        channelType: 'FILE',
        configType: 'OBJECT_AND_CHANGED',

        outputFieldPermission: {
            objectDefinitionWithPermissions: [
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'id',
                        fieldPath: '.id.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'name',
                        fieldPath: '.name.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'objectType',
                        fieldPath: '.objectType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schemaId',
                        fieldPath: '.schemaId.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'channelType',
                        fieldPath: '.channelType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'contentType',
                        fieldPath: '.contentType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'title',
                        fieldPath: '.title.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'content',
                        fieldPath: '.content.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'configType',
                        fieldPath: '.configType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schema',
                        fieldPath: '.schema.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
            ],
        },
    },
    {
        id: 256,
        name: 'Biên bản nghiệm thu đợt v1.1 (VIE)',
        objectType: 'MEDIA_PLAN',
        contentType: 'HTML',
        channelType: 'FILE',
        configType: 'OBJECT_AND_CHANGED',

        outputFieldPermission: {
            objectDefinitionWithPermissions: [
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'id',
                        fieldPath: '.id.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'name',
                        fieldPath: '.name.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'objectType',
                        fieldPath: '.objectType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schemaId',
                        fieldPath: '.schemaId.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'channelType',
                        fieldPath: '.channelType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'contentType',
                        fieldPath: '.contentType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'title',
                        fieldPath: '.title.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'content',
                        fieldPath: '.content.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'configType',
                        fieldPath: '.configType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schema',
                        fieldPath: '.schema.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
            ],
        },
    },
    {
        id: 235,
        name: 'test refactor',
        objectType: 'MEDIA_PLAN',
        contentType: 'HTML',
        channelType: 'FILE',
        configType: 'OBJECT_AND_CHANGED',

        outputFieldPermission: {
            objectDefinitionWithPermissions: [
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'id',
                        fieldPath: '.id.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'name',
                        fieldPath: '.name.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'objectType',
                        fieldPath: '.objectType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schemaId',
                        fieldPath: '.schemaId.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'channelType',
                        fieldPath: '.channelType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'contentType',
                        fieldPath: '.contentType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'title',
                        fieldPath: '.title.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'content',
                        fieldPath: '.content.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'configType',
                        fieldPath: '.configType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schema',
                        fieldPath: '.schema.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
            ],
        },
    },
    {
        id: 234,
        name: 'Gửi thông tin nghiệm thu (NEW)',
        objectType: 'MEDIA_PLAN',
        contentType: 'HTML',
        channelType: 'EMAIL',
        configType: 'OBJECT_AND_CHANGED',

        outputFieldPermission: {
            objectDefinitionWithPermissions: [
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'id',
                        fieldPath: '.id.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'name',
                        fieldPath: '.name.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'objectType',
                        fieldPath: '.objectType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schemaId',
                        fieldPath: '.schemaId.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'channelType',
                        fieldPath: '.channelType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'contentType',
                        fieldPath: '.contentType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'title',
                        fieldPath: '.title.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'content',
                        fieldPath: '.content.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'configType',
                        fieldPath: '.configType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schema',
                        fieldPath: '.schema.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
            ],
        },
    },
    {
        id: 233,
        name: '[ENG] Thông báo đối tác báo cáo issue (chỉ gửi cho Partner)',
        objectType: 'RECONCILIATION_PERIOD',
        contentType: 'HTML',
        channelType: 'EMAIL',
        configType: 'OBJECT_AND_CHANGED',

        outputFieldPermission: {
            objectDefinitionWithPermissions: [
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'id',
                        fieldPath: '.id.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'name',
                        fieldPath: '.name.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'objectType',
                        fieldPath: '.objectType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schemaId',
                        fieldPath: '.schemaId.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'channelType',
                        fieldPath: '.channelType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'contentType',
                        fieldPath: '.contentType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'title',
                        fieldPath: '.title.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'content',
                        fieldPath: '.content.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'configType',
                        fieldPath: '.configType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schema',
                        fieldPath: '.schema.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
            ],
        },
    },
    {
        id: 232,
        name: '[ENG] Thông báo đối tác báo cáo issue (chỉ gửi cho AWING)',
        objectType: 'RECONCILIATION_PERIOD',
        contentType: 'HTML',
        channelType: 'EMAIL',
        configType: 'OBJECT_AND_CHANGED',

        outputFieldPermission: {
            objectDefinitionWithPermissions: [
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'id',
                        fieldPath: '.id.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'name',
                        fieldPath: '.name.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'objectType',
                        fieldPath: '.objectType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schemaId',
                        fieldPath: '.schemaId.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'channelType',
                        fieldPath: '.channelType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'contentType',
                        fieldPath: '.contentType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'title',
                        fieldPath: '.title.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'content',
                        fieldPath: '.content.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'configType',
                        fieldPath: '.configType.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
                {
                    permission: 31,
                    objectDefinition: {
                        fieldName: 'schema',
                        fieldPath: '.schema.',
                        objectTypeCode: 'TEMPLATE',
                    },
                },
            ],
        },
    },
];

export const initObjectDefinitions: ObjectDefinition[] = [
    {
        id: 1,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'name',
        fieldPath: '.name.',
        fieldType: '',
        description: '',
    },
    {
        id: 2,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'parentDirectoryId',
        fieldPath: '.parentDirectoryId.',
        fieldType: '',
        description: '',
    },
    {
        id: 3,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'refId',
        fieldPath: '.refId.',
        fieldType: '',
        description: '',
    },
    {
        id: 4,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'status',
        fieldPath: '.status.',
        fieldType: '',
        description: '',
    },
    {
        id: 5,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'vat',
        fieldPath: '.vat.',
        fieldType: '',
        description: '',
    },
    {
        id: 6,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'brandId',
        fieldPath: '.brandId.',
        fieldType: '',
        description: '',
    },
    {
        id: 7,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'mediaPlanType',
        fieldPath: '.mediaPlanType.',
        fieldType: '',
        description: '',
    },
    {
        id: 8,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'paymentCustomerId',
        fieldPath: '.paymentCustomerId.',
        fieldType: '',
        description: '',
    },
    {
        id: 9,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'billCustomerId',
        fieldPath: '.billCustomerId.',
        fieldType: '',
        description: '',
    },
    {
        id: 10,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'paymentType',
        fieldPath: '.paymentType.',
        fieldType: '',
        description: '',
    },
    {
        id: 11,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'paymentDay',
        fieldPath: '.paymentDay.',
        fieldType: '',
        description: '',
    },
    {
        id: 13,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'description',
        fieldPath: '.description.',
        fieldType: '',
        description: '',
    },
    {
        id: 14,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'bizBilledDate',
        fieldPath: '.bizBilledDate.',
        fieldType: '',
        description: '',
    },
    {
        id: 15,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'acceptanceDate',
        fieldPath: '.acceptanceDate.',
        fieldType: '',
        description: '',
    },
    {
        id: 16,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'amountSubtotal',
        fieldPath: '.amountSubtotal.',
        fieldType: '',
        description: '',
    },
    {
        id: 17,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'amountTotal',
        fieldPath: '.amountTotal.',
        fieldType: '',
        description: '',
    },
    {
        id: 18,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'buId',
        fieldPath: '.buId.',
        fieldType: '',
        description: '',
    },
    {
        id: 19,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'picId',
        fieldPath: '.picId.',
        fieldType: '',
        description: '',
    },
    {
        id: 20,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'picSupporterId',
        fieldPath: '.picSupporterId.',
        fieldType: '',
        description: '',
    },
    {
        id: 21,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'name',
        fieldPath: '.name.',
        fieldType: '',
        description: '',
    },
    {
        id: 22,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'period',
        fieldPath: '.period.',
        fieldType: '',
        description: '',
    },
    {
        id: 23,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'supplierId',
        fieldPath: '.supplierId.',
        fieldType: '',
        description: '',
    },
    {
        id: 24,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'status',
        fieldPath: '.status.',
        fieldType: '',
        description: '',
    },
    {
        id: 25,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'confirmDate',
        fieldPath: '.confirmDate.',
        fieldType: '',
        description: '',
    },
    {
        id: 26,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'amountTotal',
        fieldPath: '.amountTotal.',
        fieldType: '',
        description: '',
    },
    {
        id: 27,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'amountSharedTotal',
        fieldPath: '.amountSharedTotal.',
        fieldType: '',
        description: '',
    },
    {
        id: 28,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'createdDate',
        fieldPath: '.createdDate.',
        fieldType: '',
        description: '',
    },
    {
        id: 29,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'id',
        fieldPath: '.id.',
        fieldType: '',
        description: '',
        isPrimaryKey: true,
    },
    {
        id: 30,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'brand',
        fieldPath: '.brand.',
        fieldType: '',
        description: '',
    },
    {
        id: 31,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'paymentCustomer',
        fieldPath: '.paymentCustomer.',
        fieldType: '',
        description: '',
    },
    {
        id: 32,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'billCustomer',
        fieldPath: '.billCustomer.',
        fieldType: '',
        description: '',
    },
    {
        id: 33,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'paymentDueDate',
        fieldPath: '.paymentDueDate.',
        fieldType: '',
        description: '',
    },
    {
        id: 34,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'businessUnit',
        fieldPath: '.businessUnit.',
        fieldType: '',
        description: '',
    },
    {
        id: 35,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'pic',
        fieldPath: '.pic.',
        fieldType: '',
        description: '',
    },
    {
        id: 36,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'picSupporter',
        fieldPath: '.picSupporter.',
        fieldType: '',
        description: '',
    },
    {
        id: 37,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'mediaPlanUnitPrices',
        fieldPath: '.mediaPlanUnitPrices.',
        fieldType: '',
        description: '',
    },
    {
        id: 38,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'id',
        fieldPath: '.mediaPlanUnitPrices.id.',
        fieldType: '',
        description: '',
    },
    {
        id: 39,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'type',
        fieldPath: '.mediaPlanUnitPrices.type.',
        fieldType: '',
        description: '',
    },
    {
        id: 40,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'quantity',
        fieldPath: '.mediaPlanUnitPrices.quantity.',
        fieldType: '',
        description: '',
    },
    {
        id: 41,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'quantityFocPercentage',
        fieldPath: '.mediaPlanUnitPrices.quantityFocPercentage.',
        fieldType: '',
        description: '',
    },
    {
        id: 42,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'quantityBonus',
        fieldPath: '.mediaPlanUnitPrices.quantityBonus.',
        fieldType: '',
        description: '',
    },
    {
        id: 43,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'listPrice',
        fieldPath: '.mediaPlanUnitPrices.listPrice.',
        fieldType: '',
        description: '',
    },
    {
        id: 44,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'priceDiscountRatePercentage',
        fieldPath: '.mediaPlanUnitPrices.priceDiscountRatePercentage.',
        fieldType: '',
        description: '',
    },
    {
        id: 45,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'netPrice',
        fieldPath: '.mediaPlanUnitPrices.netPrice.',
        fieldType: '',
        description: '',
    },
    {
        id: 46,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'mediaPlanUnitPriceSuppliers',
        fieldPath: '.mediaPlanUnitPrices.mediaPlanUnitPriceSuppliers.',
        fieldType: '',
        description: '',
    },
    {
        id: 47,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: '{customerId}',
        fieldPath: '.mediaPlanUnitPrices.mediaPlanUnitPriceSuppliers.{customerId}.',
        fieldType: '',
        description: 'customerId',
    },
    {
        id: 48,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'mediaPlanPayments',
        fieldPath: '.mediaPlanPayments.',
        fieldType: '',
        description: '',
    },
    {
        id: 51,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'mediaPlanCampaigns',
        fieldPath: '.mediaPlanCampaigns.',
        fieldType: '',
        description: '',
    },
    {
        id: 52,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'id',
        fieldPath: '.id.',
        fieldType: '',
        description: '',
        isPrimaryKey: true,
    },
    {
        id: 53,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'supplier',
        fieldPath: '.supplier.',
        fieldType: '',
        description: '',
    },
    {
        id: 54,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'reconciliationPayments',
        fieldPath: '.reconciliationPayments.',
        fieldType: '',
        description: '',
    },
    {
        id: 55,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'reconciliationMediaPlans',
        fieldPath: '.reconciliationMediaPlans.',
        fieldType: '',
        description: '',
    },
    {
        id: 56,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'bu',
        fieldPath: '.bu.',
        fieldType: '',
        description: '',
    },
    {
        id: 57,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'name',
        fieldPath: '.mediaPlanUnitPrices.name.',
        fieldType: '',
        description: '',
    },
    {
        id: 58,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'adUnit',
        fieldPath: '.mediaPlanUnitPrices.adUnit.',
        fieldType: '',
        description: '',
    },
    {
        id: 59,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'description',
        fieldPath: '.mediaPlanUnitPrices.description.',
        fieldType: '',
        description: '',
    },
    {
        id: 60,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'mediaPlanAcceptances',
        fieldPath: '.mediaPlanAcceptances.',
        fieldType: '',
        description: '',
    },
    {
        id: 61,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: '{customerId}',
        fieldPath: '.mediaPlanAcceptances.{customerId}.',
        fieldType: '',
        description: '',
    },
    {
        id: 62,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'mediaPlanAcceptanceFiles',
        fieldPath: '.mediaPlanAcceptanceFiles.',
        fieldType: '',
        description: '',
    },
    {
        id: 63,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: '{customerId}',
        fieldPath: '.mediaPlanAcceptanceFiles.{customerId}.',
        fieldType: '',
        description: '',
    },
    {
        id: 64,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'mediaPlanAcceptanceFileSuppliers',
        fieldPath: '.mediaPlanAcceptanceFileSuppliers.',
        fieldType: '',
        description: '',
    },
    {
        id: 65,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: '{customerId}',
        fieldPath: '.mediaPlanAcceptanceFileSuppliers.{customerId}.',
        fieldType: '',
        description: '',
    },
    {
        id: 66,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'mediaPlanAcceptanceFileIdRemoves',
        fieldPath: '.mediaPlanAcceptanceFileIdRemoves.',
        fieldType: '',
        description: '',
    },
    {
        id: 67,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'mediaPlanAcceptanceAdjustments',
        fieldPath: '.mediaPlanAcceptanceAdjustments.',
        fieldType: '',
        description: '',
    },
    {
        id: 68,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'receiptedDate',
        fieldPath: '.receiptedDate.',
        fieldType: '',
        description: '',
    },
    {
        id: 69,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'customerId',
        fieldPath: '.customerId.',
        fieldType: '',
        description: '',
    },
    {
        id: 70,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'reconciliationMediaPlanDescriptions',
        fieldPath: '.reconciliationMediaPlanDescriptions.',
        fieldType: '',
        description: '',
    },
    {
        id: 71,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'revenueSharingRate',
        fieldPath: '.revenueSharingRate.',
        fieldType: '',
        description: '',
    },
    {
        id: 72,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'vat',
        fieldPath: '.vat.',
        fieldType: '',
        description: '',
    },
    {
        id: 73,
        objectTypeCode: 'MENU',
        fieldName: 'id',
        fieldPath: '.id.',
        fieldType: '',
        description: '',
        isPrimaryKey: true,
    },
    {
        id: 74,
        objectTypeCode: 'MENU',
        fieldName: 'name',
        fieldPath: '.name.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 75,
        objectTypeCode: 'MENU',
        fieldName: 'key',
        fieldPath: '.key.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 76,
        objectTypeCode: 'MENU',
        fieldName: 'order',
        fieldPath: '.order.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 77,
        objectTypeCode: 'MENU',
        fieldName: 'parentId',
        fieldPath: '.parentId.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 78,
        objectTypeCode: 'TEMPLATE',
        fieldName: 'id',
        fieldPath: '.id.',
        fieldType: '',
        description: '',
        isPrimaryKey: true,
    },
    {
        id: 79,
        objectTypeCode: 'TEMPLATE',
        fieldName: 'name',
        fieldPath: '.name.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 80,
        objectTypeCode: 'TEMPLATE',
        fieldName: 'objectType',
        fieldPath: '.objectType.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 81,
        objectTypeCode: 'TEMPLATE',
        fieldName: 'schemaId',
        fieldPath: '.schemaId.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 82,
        objectTypeCode: 'TEMPLATE',
        fieldName: 'channelType',
        fieldPath: '.channelType.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 83,
        objectTypeCode: 'TEMPLATE',
        fieldName: 'contentType',
        fieldPath: '.contentType.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 84,
        objectTypeCode: 'TEMPLATE',
        fieldName: 'title',
        fieldPath: '.title.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 85,
        objectTypeCode: 'TEMPLATE',
        fieldName: 'content',
        fieldPath: '.content.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 86,
        objectTypeCode: 'TEMPLATE',
        fieldName: 'configType',
        fieldPath: '.configType.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 87,
        objectTypeCode: 'TEMPLATE',
        fieldName: 'schema',
        fieldPath: '.schema.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 88,
        objectTypeCode: 'OBJECT_FILTER',
        fieldName: 'id',
        fieldPath: '.id.',
        fieldType: '',
        description: '',
        isPrimaryKey: true,
    },
    {
        id: 89,
        objectTypeCode: 'OBJECT_FILTER',
        fieldName: 'name',
        fieldPath: '.name.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 90,
        objectTypeCode: 'OBJECT_FILTER',
        fieldName: 'objectType',
        fieldPath: '.objectType.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 91,
        objectTypeCode: 'OBJECT_FILTER',
        fieldName: 'logicalExpression',
        fieldPath: '.logicalExpression.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 92,
        objectTypeCode: 'OBJECT_FILTER',
        fieldName: 'configType',
        fieldPath: '.configType.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 93,
        objectTypeCode: 'NOTIFICATION_CONFIG',
        fieldName: 'id',
        fieldPath: '.id.',
        fieldType: '',
        description: '',
        isPrimaryKey: true,
    },
    {
        id: 94,
        objectTypeCode: 'NOTIFICATION_CONFIG',
        fieldName: 'name',
        fieldPath: '.name.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 95,
        objectTypeCode: 'NOTIFICATION_CONFIG',
        fieldName: 'objectType',
        fieldPath: '.objectType.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 96,
        objectTypeCode: 'NOTIFICATION_CONFIG',
        fieldName: 'transactionType',
        fieldPath: '.transactionType.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 97,
        objectTypeCode: 'NOTIFICATION_CONFIG',
        fieldName: 'status',
        fieldPath: '.status.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 98,
        objectTypeCode: 'NOTIFICATION_CONFIG',
        fieldName: 'notificationConfigDetails',
        fieldPath: '.notificationConfigDetails.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 99,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'id',
        fieldPath: '.id.',
        fieldType: '',
        description: '',
        isPrimaryKey: true,
    },
    {
        id: 100,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'name',
        fieldPath: '.name.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 101,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'objectType',
        fieldPath: '.objectType.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 102,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'scheduleType',
        fieldPath: '.scheduleType.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 103,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'scheduleSummary',
        fieldPath: '.scheduleSummary.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 104,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'scheduleIntervalDaysOfWeek',
        fieldPath: '.scheduleIntervalDaysOfWeek.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 105,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'scheduleIntervalDaysOfMonth',
        fieldPath: '.scheduleIntervalDaysOfMonth.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 106,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'scheduleIntervalFromTime',
        fieldPath: '.scheduleIntervalFromTime.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 107,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'scheduleIntervalEndTime',
        fieldPath: '.scheduleIntervalEndTime.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 108,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'scheduleStartDate',
        fieldPath: '.scheduleStartDate.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 109,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'scheduleIntervalInMinutes',
        fieldPath: '.scheduleIntervalInMinutes.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 110,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'scheduleToDate',
        fieldPath: '.scheduleToDate.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 111,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'scheduleExpression',
        fieldPath: '.scheduleExpression.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 112,
        objectTypeCode: 'SUBSCRIPTION_CONFIG',
        fieldName: 'subscriptionConfigDetails',
        fieldPath: '.subscriptionConfigDetails.',
        fieldType: '',
        description: '',
        isPrimaryKey: false,
    },
    {
        id: 113,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'agencyFee',
        fieldPath: '.agencyFee.',
        fieldType: '',
        description: '',
    },
    {
        id: 114,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'contractSigningDate',
        fieldPath: '.contractSigningDate.',
        fieldType: '',
        description: '',
    },
    {
        id: 115,
        objectTypeCode: 'REPORT',
        fieldName: 'id',
        fieldPath: '.id.',
        fieldType: '',
        description: '',
        isPrimaryKey: true,
    },
    {
        id: 116,
        objectTypeCode: 'REPORT',
        fieldName: 'name',
        fieldPath: '.name.',
        fieldType: '',
        description: '',
    },
    {
        id: 117,
        objectTypeCode: 'REPORT',
        fieldName: 'groups',
        fieldPath: '.groups.',
        fieldType: '',
        description: '',
    },
    {
        id: 118,
        objectTypeCode: 'REPORT',
        fieldName: 'charts',
        fieldPath: '.charts.',
        fieldType: '',
        description: '',
    },
    {
        id: 119,
        objectTypeCode: 'REPORT',
        fieldName: 'reportColumnDefinitions',
        fieldPath: '.reportColumnDefinitions.',
        fieldType: '',
        description: '',
    },
    {
        id: 120,
        objectTypeCode: 'REPORT',
        fieldName: 'id',
        fieldPath: '.reportColumnDefinitions.id.',
        fieldType: '',
        description: '',
    },
    {
        id: 121,
        objectTypeCode: 'REPORT',
        fieldName: 'field',
        fieldPath: '.reportColumnDefinitions.field.',
        fieldType: '',
        description: '',
    },
    {
        id: 122,
        objectTypeCode: 'REPORT',
        fieldName: 'reportDefinitionId',
        fieldPath: '.reportColumnDefinitions.reportDefinitionId.',
        fieldType: '',
        description: '',
    },
    {
        id: 123,
        objectTypeCode: 'REPORT',
        fieldName: 'summarize',
        fieldPath: '.reportColumnDefinitions.summarize.',
        fieldType: '',
        description: '',
    },
    {
        id: 124,
        objectTypeCode: 'REPORT',
        fieldName: 'reportFilterDefinitions',
        fieldPath: '.reportFilterDefinitions.',
        fieldType: '',
        description: '',
    },
    {
        id: 125,
        objectTypeCode: 'REPORT',
        fieldName: 'id',
        fieldPath: '.reportFilterDefinitions.id.',
        fieldType: '',
        description: '',
    },
    {
        id: 126,
        objectTypeCode: 'REPORT',
        fieldName: 'field',
        fieldPath: '.reportFilterDefinitions.field.',
        fieldType: '',
        description: '',
    },
    {
        id: 127,
        objectTypeCode: 'REPORT',
        fieldName: 'isRequired',
        fieldPath: '.reportFilterDefinitions.isRequired.',
        fieldType: '',
        description: '',
    },
    {
        id: 128,
        objectTypeCode: 'REPORT',
        fieldName: 'operator',
        fieldPath: '.reportFilterDefinitions.operator.',
        fieldType: '',
        description: '',
    },
    {
        id: 129,
        objectTypeCode: 'REPORT',
        fieldName: 'reportDefinitionId',
        fieldPath: '.reportFilterDefinitions.reportDefinitionId.',
        fieldType: '',
        description: '',
    },
    {
        id: 130,
        objectTypeCode: 'REPORT',
        fieldName: 'value',
        fieldPath: '.reportFilterDefinitions.value.',
        fieldType: '',
        description: '',
    },
    {
        id: 131,
        objectTypeCode: 'RECONCILIATION_PERIOD',
        fieldName: 'revenueSharingTotal',
        fieldPath: '.revenueSharingTotal.',
        fieldType: '',
        description: '',
    },
    {
        id: 132,
        objectTypeCode: 'MEDIA_PLAN',
        fieldName: 'agencyDiscountRateForBrand',
        fieldPath: '.agencyDiscountRateForBrand.',
        fieldType: '',
        description: '',
    },
];
