export enum FIELD_TYPE {
    TEXT = 'text',
    EMAIL = 'email',
    TEL = 'tel',
    TEXT_AREA = 'text-area',
    URL = 'url',
    PASSWORD = 'password',
    NUMBER = 'number',
    DATE = 'date',
    MONTH = 'month',
    DATE_RANGE = 'date-range',
    CHECKBOX = 'checkbox',
    RADIO = 'radio',
    SELECT = 'select',
    AUTOCOMPLETE = 'autocomplete',
    ASYNC_AUTOCOMPLETE = 'async-autocomplete',
    LOGIC_EXPRESSION = 'logic-expression',
    GEO_FENCING = 'geo-fencing',
    MULTIPLE_HIERARCHICAL = 'multiple-hierarchical',
    MONACO_EDITOR = 'monaco-editor',
    SELECT_FOLDER = 'select-folder',
    CUSTOM = 'custom',
}
