import FilterTreeView from 'AWING/DirectoryTree/FilterTreeView';
import Layout from '../common/Layout';
import { Meta, StoryObj } from '@storybook/react';

// #region Meta
const meta = {
    title: 'AWING/FilterTreeView',
    parameters: {
        layout: 'padded',
    },
    tags: ['autodocs'],
    component: FilterTreeView,
} satisfies Meta<typeof FilterTreeView>;
// #endregion Meta

export type Story = StoryObj<typeof meta>;

export const Simple: Story = {
    args: {
        rootDirectoryId: 0,
        items: [
            {
                description: '',
                directoryPath: '.0.10.',
                value: 10,
                isFile: false,
                isSystem: true,
                level: 1,
                text: 'ACM',
                objectId: 10,
                objectTypeCode: 'Directory',
                order: 0,
                parentObjectId: 0,
                actions: (
                    <div>
                        <button>action 1</button>
                        <button>action 2</button>
                    </div>
                ),
            },
            {
                description: '',
                directoryPath: '.0.10.2.',
                value: 101,
                isFile: false,
                isSystem: true,
                level: 2,
                text: 'Hệ thống',
                objectId: 2,
                objectTypeCode: 'Menu',
                order: 0,
                parentObjectId: 10,
            },
            {
                description: '',
                directoryPath: '.0.10.21.',
                value: 1005,
                isFile: false,
                isSystem: true,
                level: 2,
                text: 'SHARE',
                objectId: 21,
                objectTypeCode: 'Share',
                order: 0,
                parentObjectId: 10,
            },
            {
                description: '',
                directoryPath: '.0.10.21.1006.',
                value: 1006,
                isFile: false,
                isSystem: true,
                level: 3,
                text: 'Cấu hình chia sẻ 1',
                objectId: 1006,
                objectTypeCode: 'Directory',
                order: 0,
                parentObjectId: 21,
            },
            {
                description: '',
                directoryPath: '.0.10.21.1006.2.',
                value: 1008,
                isFile: true,
                isSystem: false,
                level: 4,
                text: 'Hệ thống',
                objectId: 2,
                objectTypeCode: 'Menu',
                order: 0,
                parentObjectId: 1006,
            },
            {
                description: '',
                directoryPath: '.0.10.21.1006.10.',
                value: 1011,
                isFile: true,
                isSystem: false,
                level: 4,
                text: 'Campaign',
                objectId: 10,
                objectTypeCode: 'Menu',
                order: 0,
                parentObjectId: 1006,
                actions: (
                    <div>
                        <button>action 1</button>
                        <button>action 2</button>
                    </div>
                ),
            },
            {
                description: '',
                directoryPath: '.0.10.9.',
                value: 1113,
                isFile: false,
                isSystem: true,
                level: 2,
                text: 'Campaign',
                objectId: 9,
                objectTypeCode: 'Directory',
                order: 0,
                parentObjectId: 10,
                actions: (
                    <div>
                        <button>action 1</button>
                        <button>action 2</button>
                    </div>
                ),
            },
            {
                description: '',
                directoryPath: '.0.10.9.1115.',
                value: 1115,
                isFile: false,
                isSystem: false,
                level: 3,
                text: 'test-campaign',
                objectId: 1115,
                objectTypeCode: 'Directory',
                order: 0,
                parentObjectId: 9,
            },
            {
                description: '',
                directoryPath: '.0.10.9.1116.',
                value: 1116,
                isFile: false,
                isSystem: false,
                level: 3,
                text: 'test123-campaign',
                objectId: 1116,
                objectTypeCode: 'Directory',
                order: 0,
                parentObjectId: 9,
            },
            {
                description: '',
                directoryPath: '.0.10.21.1006.24.',
                value: 1142,
                isFile: true,
                isSystem: false,
                level: 4,
                text: 'Địa điểm',
                objectId: 24,
                objectTypeCode: 'Menu',
                order: 0,
                parentObjectId: 1006,
            },
            {
                description: '',
                directoryPath: '.0.10.21.1006.27.',
                value: 1143,
                isFile: true,
                isSystem: false,
                level: 4,
                text: 'Nhóm địa điểm',
                objectId: 27,
                objectTypeCode: 'Menu',
                order: 0,
                parentObjectId: 1006,
            },
            {
                description: '',
                directoryPath: '.0.10.3.',
                value: 1144,
                isFile: false,
                isSystem: true,
                level: 2,
                text: 'location',
                objectId: 3,
                objectTypeCode: 'Menu',
                order: 0,
                parentObjectId: 10,
            },
            {
                description: '',
                directoryPath: '.0.10.24.',
                value: 1145,
                isFile: false,
                isSystem: true,
                level: 2,
                text: 'PlaceRoot',
                objectId: 24,
                objectTypeCode: 'Directory',
                order: 0,
                parentObjectId: 10,
            },
            {
                description: '',
                directoryPath: '.0.10.13.',
                value: 1152,
                isFile: false,
                isSystem: false,
                level: 2,
                text: 'AuthenticationProfile',
                objectId: 13,
                objectTypeCode: 'Directory',
                order: 0,
                parentObjectId: 10,
            },
            {
                description: '',
                directoryPath: '.0.10.15.',
                value: 1157,
                isFile: false,
                isSystem: true,
                level: 2,
                text: 'PlaceGroup',
                objectId: 15,
                objectTypeCode: 'Directory',
                order: 0,
                parentObjectId: 10,
            },
            {
                description: '',
                directoryPath: '.0.10.6.',
                value: 1159,
                isFile: false,
                isSystem: true,
                level: 2,
                text: 'Page',
                objectId: 6,
                objectTypeCode: 'Directory',
                order: 0,
                parentObjectId: 10,
            },
            {
                description: '',
                directoryPath: '.0.10.21.1006.26.',
                value: 1161,
                isFile: true,
                isSystem: false,
                level: 4,
                text: 'Access Point',
                objectId: 26,
                objectTypeCode: 'Menu',
                order: 0,
                parentObjectId: 1006,
            },
            {
                description: '',
                directoryPath: '.0.10.7.',
                value: 1162,
                isFile: false,
                isSystem: true,
                level: 2,
                text: 'Schema',
                objectId: 7,
                objectTypeCode: 'Directory',
                order: 0,
                parentObjectId: 10,
            },
            {
                description: '',
                directoryPath: '.0.10.15.18.',
                value: 1257,
                isFile: true,
                isSystem: false,
                level: 3,
                text: 'Test nhóm Place1',
                objectId: 18,
                objectTypeCode: 'PlaceGroup',
                order: 0,
                parentObjectId: 15,
            },
            {
                description: '',
                directoryPath: '.0.10.28.',
                value: 1258,
                isFile: false,
                isSystem: true,
                level: 2,
                text: 'Attribute',
                objectId: 28,
                objectTypeCode: 'Directory',
                order: 0,
                parentObjectId: 10,
            },
            {
                description: '',
                directoryPath: '.0.10.28.27.',
                value: 1259,
                isFile: true,
                isSystem: false,
                level: 3,
                text: 'Test 22',
                objectId: 27,
                objectTypeCode: 'Attribute',
                order: 0,
                parentObjectId: 28,
            },
            {
                description: '',
                directoryPath: '.0.10.28.28.',
                value: 1260,
                isFile: true,
                isSystem: false,
                level: 3,
                text: 'Tesst lab',
                objectId: 28,
                objectTypeCode: 'Attribute',
                order: 0,
                parentObjectId: 28,
            },
        ],
        onDirectoryOpen: (id: any) => console.log(id),
        onTreeItemClick: () => {},
    },
    render: (args) => {
        return (
            <Layout>
                <div style={{ minWidth: 400 }}>
                    <FilterTreeView {...args} />
                </div>
            </Layout>
        );
    },
};

export default meta;
