export enum TYPE_FILTERS {
    VIEW_BY = 'ViewBy',
    VIEW_TIME = 'ViewTime',
    VIEW_COMPLETION_RATE = 'ViewCompletionRate',
    VIEW_USER = 'ViewUser',
    CAMPAIGN = 'Campaign',
    PLACE = 'Place',
    PLACE_AUTOCOMPLETE = 'PlaceAutoComplete',
    DOMAIN_AUTOCOMPLETE = 'DomainAutoComplete',
    CAMPAIGN_AUTOCOMPLETE = 'CampaignAutoComplete',
    NETWORK = 'NetWork',
    CAMPAIGN_DEFAULT = 'CampaignDefault',
    INCLUDE_RESERVED = 'IncludeReserved',
    DATE_RANGE_PICKER = 'DateRangePicker',
    SEARCH_BY_PLACE = 'SearchByPlace',
    SEARCH_CAMPAIGNS = 'SearchCampaigns',
    SELECT = 'Select',
}
