import { CurrentWorkspace } from 'Features/SYSTEM/types';
import { ObjectDefinition } from 'AWING/DirectoryPermission/types';

export const currentWorkspace: CurrentWorkspace = {
    customerId: 10,
    customerType: 'Customer Type 10',
    description: 'Description 10',
    id: 10,
    isJoinNetwork: true,
    name: 'Workspace 10',
    type: 'ACM',
    url: 'Url 5',
    defaultSchemas: [
        {
            id: 1,
            name: 'Default Schema',
            objectTypeCode: 'Campaign',
            workspaceId: 0,
            schemaObjectDefinitions: [
                {
                    id: 2,
                    isReadOnly: false,
                    objectDefinitionId: 2,
                    schemaId: 1,
                    objectDefinition: {
                        fieldName: 'id',
                        fieldPath: '.id.',
                        id: 2,
                        isPrimaryKey: true,
                        objectTypeCode: 'Campaign',
                    },
                },
                {
                    id: 3,
                    isReadOnly: true,
                    objectDefinitionId: 3,
                    schemaId: 1,
                    objectDefinition: {
                        fieldName: 'name',
                        fieldPath: '.name.',
                        id: 3,
                        objectTypeCode: 'Campaign',
                    },
                },
            ],
        },
    ],
};

export const ObjectTyeCodes = {
    none: 0,
    menu: 2,
    workflow: 3,
    group: 4,
    campaign: 5,
    page: 6,
    schema: 7,
    archive: 8,
    page_welcome: 9,
    page_login: 10,
    template: 11,
    layout: 12,
    authentication_profile: 13,
    ap: 14,
    place_group: 15,
    wizard: 16,
    campaign_collection: 17,
    task_scheduler: 18,
    object_filter: 19,
    role: 20,
    share: 21,
    workspace: 22,
    user: 23,
    place: 24,
    role_tag: 25,
    transaction_log: 26,
    attribute_type: 27,
    attribute: 28,
    holiday: 29,
    place_customer_info_collection: 30,
};

export const objectDefinitions: ObjectDefinition[] = [
    {
        description: '',
        fieldName: 'field1',
        fieldPath: '.field1.',
        id: 4,
        isPrimaryKey: false,
        objectTypeCode: 'Campaign',
    },
    {
        description: '',
        fieldName: 'field2',
        fieldPath: '.field2.',
        id: 5,
        isPrimaryKey: false,
        objectTypeCode: 'Campaign',
    },
    {
        description: '',
        fieldName: 'id',
        fieldPath: '.id.',
        id: 2,
        isPrimaryKey: true,
        objectTypeCode: 'Campaign',
    },
    {
        description: '',
        fieldName: 'name',
        fieldPath: '.name.',
        id: 3,
        isPrimaryKey: false,
        objectTypeCode: 'Campaign',
    },
    {
        description: '',
        fieldName: 'root1',
        fieldPath: '.root1.',
        id: 9,
        isPrimaryKey: false,
        objectTypeCode: 'Campaign',
    },
    {
        description: '',
        fieldName: 'idOfRoot',
        fieldPath: '.root1.idOfRoot.',
        id: 10,
        isPrimaryKey: false,
        objectTypeCode: 'Campaign',
    },
    {
        description: '',
        fieldName: 'nameOfRoot',
        fieldPath: '.root1.nameOfRoot.',
        id: 11,
        isPrimaryKey: false,
        objectTypeCode: 'Campaign',
    },
    {
        description: '',
        fieldName: 'field1',
        fieldPath: '.field1.',
        id: 8,
        isPrimaryKey: false,
        objectTypeCode: 'Place',
    },
    {
        description: '',
        fieldName: 'id',
        fieldPath: '.id.',
        id: 6,
        isPrimaryKey: true,
        objectTypeCode: 'Place',
    },
    {
        description: '',
        fieldName: 'name',
        fieldPath: '.name.',
        id: 7,
        isPrimaryKey: false,
        objectTypeCode: 'Place',
    },
    {
        description: '',
        fieldName: 'root1',
        fieldPath: '.root1.',
        id: 12,
        isPrimaryKey: false,
        objectTypeCode: 'Place',
    },
    {
        description: '',
        fieldName: 'id',
        fieldPath: '.root1.id.',
        id: 13,
        isPrimaryKey: false,
        objectTypeCode: 'Place',
    },
    {
        description: '',
        fieldName: 'name',
        fieldPath: '.root1.name.',
        id: 14,
        isPrimaryKey: false,
        objectTypeCode: 'Place',
    },
    {
        description: '',
        fieldName: 'root2',
        fieldPath: '.root1.root2.',
        id: 15,
        isPrimaryKey: false,
        objectTypeCode: 'Place',
    },
    {
        description: '',
        fieldName: 'id',
        fieldPath: '.root1.root2.id.',
        id: 16,
        isPrimaryKey: false,
        objectTypeCode: 'Place',
    },
    {
        description: '',
        fieldName: 'name',
        fieldPath: '.root1.root2.name.',
        id: 17,
        isPrimaryKey: false,
        objectTypeCode: 'Place',
    },
];

export const directoryBasic = {
    description: '',
    directoryPath: '.0.10.21.1006.27.',
    id: 1143,
    isFile: false,
    isSystem: false,
    level: 4,
    name: 'Nhóm địa điểm',
    objectId: 27,
    objectTypeCode: 'Menu',
    order: 0,
    parentObjectId: 1006,
    explicitPermissions: [
        {
            authenName: 'test',
            authenType: 'USER',
            authenValue: 1029,
            directoryId: 1143,
            directoryPath: '.0.10.21.1006.27.',
            id: 1,
            permission: 1,
            objectTypeCode: 'None',
        },
        {
            authenName: 'Update name test',
            authenType: 'GROUP',
            authenValue: 10,
            directoryId: 1143,
            directoryPath: '.0.10.21.1006.27.',
            id: 2,
            permission: 1,
            objectTypeCode: 'None',
        },
        {
            authenName: 'Update name',
            authenType: 'ROLE',
            authenValue: 1,
            directoryId: 1143,
            directoryPath: '.0.10.21.1006.27.',
            id: 3,
            permission: 1,
            objectTypeCode: 'Campaign',
        },
    ],
    explicitWorkflowMatrixPermissions: [],
    inheritedPermissions: [],
    inheritedWorkflowMatrixPermissions: [],
};

export const directoryHasWorkflowState = {
    description: '',
    directoryPath: '.0.10.9.1115.73.',
    id: 1261,
    isFile: false,
    isSystem: false,
    level: 4,
    name: 'Tổng đã chọn: 1',
    objectId: 73,
    objectTypeCode: 'Campaign',
    order: 0,
    parentObjectId: 1115,
    explicitPermissions: [
        {
            authenName: 'Update name test',
            authenType: 'GROUP',
            authenValue: 10,
            directoryId: 1261,
            directoryPath: '.0.10.9.1115.73.',
            id: 4,
            permission: 3,
            schemaId: 33,
            workflowStateId: '1.1.',
            objectTypeCode: 'Campaign',
        },
        {
            authenName: 'Update name',
            authenType: 'ROLE',
            authenValue: 1,
            directoryId: 1261,
            directoryPath: '.0.10.9.1115.73.',
            id: 5,
            permission: 3,
            schemaId: null,
            workflowStateId: '1.1.400.',
            objectTypeCode: 'Campaign',
        },
        {
            authenName: 'test',
            authenType: 'GROUP',
            authenValue: 31,
            directoryId: 1261,
            directoryPath: '.0.10.9.1115.73.',
            id: 11,
            permission: 1,
            schemaId: 45,
            workflowStateId: '1.1.600.',
            objectTypeCode: 'Campaign',
        },
        {
            authenName: 'a Thử',
            authenType: 'ROLE',
            authenValue: 34,
            directoryId: 1261,
            directoryPath: '.0.10.9.1115.73.',
            id: 12,
            permission: 1,
            schemaId: 45,
            workflowStateId: '1.1.600.',
            objectTypeCode: 'Campaign',
        },
    ],
    inheritedPermissions: [
        {
            authenName: 'Update name',
            authenType: 'ROLE',
            authenValue: 1,
            directoryId: 10,
            directoryPath: '.0.10.',
            id: 20,
            permission: 1,
            schemaId: 1,
            workflowStateId: null,
            objectTypeCode: 'None',
        },
        {
            authenName: 'Tiệm Trần',
            authenType: 'USER',
            authenValue: 2049,
            directoryId: 1113,
            directoryPath: '.0.10.9.',
            id: 77,
            permission: 3,
            schemaId: 1,
            workflowStateId: null,
            objectTypeCode: 'None',
        },
    ],
    explicitWorkflowMatrixPermissions: [],
    inheritedWorkflowMatrixPermissions: [],
    workflow: {
        description: '',
        id: 1,
        name: 'Campaign',
        objectTypeCode: 'Campaign',
        stateFieldName: 'status',
        workflowMatrices: [
            {
                id: 1,
                priority: 0,
                stateEnd: '1.1.',
                stateStart: '1.1.',
                workflowId: 1,
            },
        ],
        workflowStates: [
            {
                id: '1.1.',
                level: 0,
                name: 'DEFAULT',
                parentId: null,
                priority: 0,
                value: 1,
                workflowId: 1,
            },
            {
                id: '1.1.100.',
                level: 1,
                name: 'CREATED',
                parentId: '1.1.',
                priority: 0,
                value: 100,
                workflowId: 1,
            },
            {
                id: '1.1.300.',
                level: 1,
                name: 'RUNNING',
                parentId: '1.1.',
                priority: 0,
                value: 300,
                workflowId: 1,
            },
            {
                id: '1.1.400.',
                level: 1,
                name: 'ACCEPTANCE',
                parentId: '1.1.',
                priority: 0,
                value: 400,
                workflowId: 1,
            },
            {
                id: '1.1.500.',
                level: 1,
                name: 'PAYMENT',
                parentId: '1.1.',
                priority: 0,
                value: 500,
                workflowId: 1,
            },
            {
                id: '1.1.600.',
                level: 1,
                name: 'FINISHED',
                parentId: '1.1.',
                priority: 0,
                value: 600,
                workflowId: 1,
            },
        ],
    },
};

export const users = [
    {
        description: 'abc',
        gender: 1,
        id: 2049,
        image: '',
        name: 'Tiệm Trần',
        syncId: 2049,
        username: 'tiemtv@awing.vn',
        roleAuthens: [
            {
                id: 11,
                roleId: 1,
                userId: 2049,
            },
        ],
    },
    {
        description: '',
        gender: 1,
        id: 2050,
        image: '',
        syncId: 2049,
        username: 'demo@awing.vn',
        roleAuthens: [],
    },
];

export const roles = [
    {
        description: 'demo',
        id: 4,
        name: 'Role 01 update',
        workspaceId: 10,
        roleAuthens: [],
        roleTags: [
            {
                description: 'thử tạo mới',
                id: 5,
                name: 'Tạo mới RoleTag',
                workspaceId: 10,
            },
        ],
    },
    {
        description: 'sửa thông tin',
        id: 15,
        name: 'Role 03 test',
        workspaceId: 10,
        roleAuthens: [],
        roleTags: [
            {
                description: 'demo roletag 01',
                id: 3,
                name: 'RoleTag 01',
                workspaceId: 10,
            },
            {
                description: 'thử tạo mới',
                id: 5,
                name: 'Tạo mới RoleTag',
                workspaceId: 10,
            },
        ],
    },
    {
        description: '',
        id: 17,
        name: 'Role 03 update',
        workspaceId: 10,
        roleAuthens: [],
        roleTags: [],
    },
    {
        description: 'demo Role 04',
        id: 18,
        name: 'Role 04',
        workspaceId: 10,
        roleAuthens: [],
        roleTags: [],
    },
    {
        description: 'demo role 01',
        id: 23,
        name: 'Role 01',
        workspaceId: 10,
        roleAuthens: [],
        roleTags: [],
    },
    {
        description: 'Role mới',
        id: 36,
        name: 'Test tạo mới ROLE',
        workspaceId: 10,
        roleAuthens: [],
        roleTags: [],
    },
];

export const groups = [
    {
        id: 10,
        name: 'Update name test',
        description: 'Hello',
        users: [],
    },
    {
        id: 13,
        name: 'Hello123',
        description: '',
        users: [],
    },
    {
        id: 16,
        name: 'Hello1231231',
        description: '',
        users: [],
    },
    {
        id: 19,
        name: 'Ad 2',
        description: '',
        users: [],
    },
    {
        id: 20,
        name: 'Ad 1',
        description: '',
        users: [],
    },
    {
        id: 26,
        name: 'AAAA',
        description: '',
        users: [],
    },
    {
        id: 30,
        name: '12354tesst',
        description: 'dasdas',
        users: [],
    },
    {
        id: 31,
        name: 'test',
        description: '',
        users: [],
    },
    {
        id: 32,
        name: 'test',
        description: '',
        users: [],
    },
    {
        id: 33,
        name: 'test',
        description: '',
        users: [],
    },
    {
        id: 34,
        name: 'test',
        description: '',
        users: [],
    },
];

export const schemas = [
    {
        id: 33,
        name: 'Demo Campaign 01',
        objectTypeCode: 'Campaign',
        workspaceId: 10,
        schemaObjectDefinitions: [
            {
                id: 209,
                isReadOnly: true,
                objectDefinitionId: 2,
                schemaId: 33,
                objectDefinition: {
                    description: '',
                    fieldName: 'id',
                    fieldPath: '.id.',
                    id: 2,
                    isPrimaryKey: true,
                    objectTypeCode: 'Campaign',
                },
            },
        ],
    },
    {
        id: 34,
        name: 'Demo Campaign 02',
        objectTypeCode: 'Campaign',
        workspaceId: 10,
        schemaObjectDefinitions: [
            {
                id: 211,
                isReadOnly: false,
                objectDefinitionId: 2,
                schemaId: 34,
                objectDefinition: {
                    description: '',
                    fieldName: 'id',
                    fieldPath: '.id.',
                    id: 2,
                    isPrimaryKey: true,
                    objectTypeCode: 'Campaign',
                },
            },
        ],
    },
    {
        id: 35,
        name: 'Demo Place 01 update',
        objectTypeCode: 'Place',
        workspaceId: 10,
        schemaObjectDefinitions: [
            {
                id: 214,
                isReadOnly: false,
                objectDefinitionId: 6,
                schemaId: 35,
                objectDefinition: {
                    description: '',
                    fieldName: 'id',
                    fieldPath: '.id.',
                    id: 6,
                    isPrimaryKey: true,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 281,
                isReadOnly: false,
                objectDefinitionId: 7,
                schemaId: 35,
                objectDefinition: {
                    description: '',
                    fieldName: 'name',
                    fieldPath: '.name.',
                    id: 7,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 291,
                isReadOnly: true,
                objectDefinitionId: 15,
                schemaId: 35,
                objectDefinition: {
                    description: '',
                    fieldName: 'root2',
                    fieldPath: '.root1.root2.',
                    id: 15,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 292,
                isReadOnly: false,
                objectDefinitionId: 16,
                schemaId: 35,
                objectDefinition: {
                    description: '',
                    fieldName: 'id',
                    fieldPath: '.root1.root2.id.',
                    id: 16,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 293,
                isReadOnly: true,
                objectDefinitionId: 17,
                schemaId: 35,
                objectDefinition: {
                    description: '',
                    fieldName: 'name',
                    fieldPath: '.root1.root2.name.',
                    id: 17,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 294,
                isReadOnly: false,
                objectDefinitionId: 8,
                schemaId: 35,
                objectDefinition: {
                    description: '',
                    fieldName: 'field1',
                    fieldPath: '.field1.',
                    id: 8,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 295,
                isReadOnly: false,
                objectDefinitionId: 13,
                schemaId: 35,
                objectDefinition: {
                    description: '',
                    fieldName: 'id',
                    fieldPath: '.root1.id.',
                    id: 13,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
        ],
    },
    {
        id: 36,
        name: 'Demo Place 02',
        objectTypeCode: 'Place',
        workspaceId: 10,
        schemaObjectDefinitions: [
            {
                id: 217,
                isReadOnly: false,
                objectDefinitionId: 6,
                schemaId: 36,
                objectDefinition: {
                    description: '',
                    fieldName: 'id',
                    fieldPath: '.id.',
                    id: 6,
                    isPrimaryKey: true,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 223,
                isReadOnly: true,
                objectDefinitionId: 6,
                schemaId: 36,
                objectDefinition: {
                    description: '',
                    fieldName: 'id',
                    fieldPath: '.id.',
                    id: 6,
                    isPrimaryKey: true,
                    objectTypeCode: 'Place',
                },
            },
        ],
    },
    {
        id: 39,
        name: 'aaaa Test place',
        objectTypeCode: 'Place',
        workspaceId: 10,
        schemaObjectDefinitions: [
            {
                id: 255,
                isReadOnly: false,
                objectDefinitionId: 6,
                schemaId: 39,
                objectDefinition: {
                    description: '',
                    fieldName: 'id',
                    fieldPath: '.id.',
                    id: 6,
                    isPrimaryKey: true,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 259,
                isReadOnly: true,
                objectDefinitionId: 7,
                schemaId: 39,
                objectDefinition: {
                    description: '',
                    fieldName: 'name',
                    fieldPath: '.name.',
                    id: 7,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 263,
                isReadOnly: false,
                objectDefinitionId: 14,
                schemaId: 39,
                objectDefinition: {
                    description: '',
                    fieldName: 'name',
                    fieldPath: '.root1.name.',
                    id: 14,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 284,
                isReadOnly: true,
                objectDefinitionId: 8,
                schemaId: 39,
                objectDefinition: {
                    description: '',
                    fieldName: 'field1',
                    fieldPath: '.field1.',
                    id: 8,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 285,
                isReadOnly: false,
                objectDefinitionId: 13,
                schemaId: 39,
                objectDefinition: {
                    description: '',
                    fieldName: 'id',
                    fieldPath: '.root1.id.',
                    id: 13,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
        ],
    },
    {
        id: 40,
        name: 'Test schema Campaign',
        objectTypeCode: 'Campaign',
        workspaceId: 10,
        schemaObjectDefinitions: [
            {
                id: 264,
                isReadOnly: true,
                objectDefinitionId: 2,
                schemaId: 40,
                objectDefinition: {
                    description: '',
                    fieldName: 'id',
                    fieldPath: '.id.',
                    id: 2,
                    isPrimaryKey: true,
                    objectTypeCode: 'Campaign',
                },
            },
            {
                id: 265,
                isReadOnly: true,
                objectDefinitionId: 3,
                schemaId: 40,
                objectDefinition: {
                    description: '',
                    fieldName: 'name',
                    fieldPath: '.name.',
                    id: 3,
                    isPrimaryKey: false,
                    objectTypeCode: 'Campaign',
                },
            },
        ],
    },
    {
        id: 43,
        name: 'abc',
        objectTypeCode: 'Place',
        workspaceId: 10,
        schemaObjectDefinitions: [
            {
                id: 296,
                isReadOnly: true,
                objectDefinitionId: 6,
                schemaId: 43,
                objectDefinition: {
                    description: '',
                    fieldName: 'id',
                    fieldPath: '.id.',
                    id: 6,
                    isPrimaryKey: true,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 298,
                isReadOnly: false,
                objectDefinitionId: 13,
                schemaId: 43,
                objectDefinition: {
                    description: '',
                    fieldName: 'id',
                    fieldPath: '.root1.id.',
                    id: 13,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 299,
                isReadOnly: false,
                objectDefinitionId: 14,
                schemaId: 43,
                objectDefinition: {
                    description: '',
                    fieldName: 'name',
                    fieldPath: '.root1.name.',
                    id: 14,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 302,
                isReadOnly: false,
                objectDefinitionId: 17,
                schemaId: 43,
                objectDefinition: {
                    description: '',
                    fieldName: 'name',
                    fieldPath: '.root1.root2.name.',
                    id: 17,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 303,
                isReadOnly: true,
                objectDefinitionId: 8,
                schemaId: 43,
                objectDefinition: {
                    description: '',
                    fieldName: 'field1',
                    fieldPath: '.field1.',
                    id: 8,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
            {
                id: 304,
                isReadOnly: true,
                objectDefinitionId: 7,
                schemaId: 43,
                objectDefinition: {
                    description: '',
                    fieldName: 'name',
                    fieldPath: '.name.',
                    id: 7,
                    isPrimaryKey: false,
                    objectTypeCode: 'Place',
                },
            },
        ],
    },
];
